export default [
  "In case no one has told you ⁉️, they drive on the 👈 left side in 🗾 Asia!",
  "For all your highway 🛣️ listening, stay with Crash FM 💥",
  "This an 😎 awesome job. I crash in the 🌞 sun, you crash in the 🚥 traffic!",
  "Are you sure you're happy 😬 with those race times? 🏁⌛",
  "Is this a good show or what? 😏",
  "I keep it kind of real, 🙃 only sometimes. But who cares? 🤷",
  "Hello are you there? 🤔 You are?",
  "Let's keep the streets the burning! 🔥🔥",
  "❌ No Europop ridiculous 🇪🇺 stuff on these airwaves dude! 😎",
  "Can you spell Europe? 🇪🇺 I can't! 😶",
  "Time for games; how about a little 📄 paper, ✂️ scissors, & 🎸 rock!",
  "Great 🏁 circuits, great 🗺️ locations, great takedown 💥 opportunities!",
  "🏃 What are you waiting for? 🏃",
  "Do we care about pop music? 💀 Hell no!",
  "Do we care about classical music? 🎻 Hell no!",
  "🎸 Want rock? Crash! 💥",
  "Here's an ancient racing 🧐 proverb; It's better to 🔥 burnout than to 😶 fade away...",
  "I love the smell of ⛽ gasoline in the morning...",
  "First to cross the line wins! 🏁 Everyone else? Losers! 👎",
  "🚗 Pedal to the metal and metal onto metal 💥",
  "You 😎 Traffic 🚥 Boost 🔥 Clock ⌛ Get it?",
  "Boost, boost, boost people! 🔥🔥🔥"
]
